export { default as Home } from "./Home/Home";
export { default as Login } from "./Login/Login";
export { default as Register } from "./Register/Register";
export { default as Dashboard } from "./Dashboard/Dashboard";
export { default as Routines } from "./Routines/Routines";
export { default as RoutineDay } from "./RoutineDay/RoutineDay";
export { default as AddExercise } from "./AddExercise/AddExercise";
export { default as AddExerciseForm } from "./AddExerciseForm/AddExerciseForm";
export { default as NotFound } from "./NotFound/NotFound";
